# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: aws-deploy

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

env:
  SIMPLE_ENV: some-env
  CONTEXT: ${{ github.GITHUB_REF_NAME == 'prod' && 'prod' || 'dev' }}
  ROLE_TO_ASSUME: >
    ${{ github.GITHUB_REF_NAME == 'prod' &&
    '=arn:aws:iam::739768332450:role/sagebase-github-oidc-sage-ProviderRolegeniebpcinfr-18H4ACOLMLGAO' ||
    'arn:aws:iam::631692904429:role/sagebase-github-oidc-sage-ProviderRolegeniebpcinfr-1MC1H5DE711HO' }}

concurrency: ci-${{ github.ref }}

jobs:
  a-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: cat-env
        run: |
          echo SIMPLE_ENV: ${{env.SIMPLE_ENV}}
          echo GITHUB_REF_NAME:  ${{ github.GITHUB_REF_NAME }}
          echo ROLE_TO_ASSUME: ${{env.SIMPLE_ENV}}
          